### ISSUE TITLE
Please specify # make arm

### ISSUE THREAD

**Issue by ThomasHeinrichSchmidt** [kayrus/iradio#1]
I have the same kind of radio (iRadio 1) with the same CPU and very similiar firmware.
I'm trying to build an arm app for the device (just like your favlist.c) but I can't.
I've tried 
`# arm-linux-gnueabi-gcc hello.c -o hello`
`# arm-none-eabi-gcc --specs=nosys.specs hello.c -o hello`
`# arm-none-eabi-gcc --specs=nosys.specs -mcpu=arm926ej-s -static  hello.c -o hello`
`# arm-linux-gnueabihf-gcc -marm -mcpu=arm926ej-s -static hello.c -o hello`
`# arm-linux-gnueabihf-gcc -mabi=aapcs-linux -marm -mcpu=arm926ej-s -static hello.c -o hello`
but all fail to run. 
Can you please show your make? Or give me a hint which toolchain to use how?
Thanks.

**Comment by kayrus** [comment]
@ThomasHeinrichSchmidt there is no need to build the binary for arm, because its purpose is to be executed on a local Linux system and compile a binary playlist from a text file. Arm binary support was added just for fun. A regular `make` should build a binary for your Linux system in case if you installed compilers.

For arm architecture you'd need to install a cross compilation tool chain (musl or one from your destribution). For example, in Ubuntu 20.04 you can install it from the `gcc-arm-linux-gnueabi` package, or download toolchain from http://musl.codu.org/

**Comment by ThomasHeinrichSchmidt** [comment]
Thanks for your answer @kayrus I already successfully built your favlist.c, no problem.
But I was not able to build for the iradio system. I installed various tool chains (see above) but none built a working executable. Therefor I was interested if you were able to successfully build for the iradio. And which compiler settings you were using.

**Comment by kayrus** [comment]
@ThomasHeinrichSchmidt `favlist.c` can be successfully built on ubuntu 20.04:

```
$ sudo apt install gcc-arm-linux-gnueabi -y
$ make arm
arm-linux-gnueabi-gcc -Wall -g -static -o favlist_arm favlist.c
$ file favlist_arm
favlist_arm: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, BuildID[sha1]=5bd8ba1536f3b7b741e66bd45be962089c8aff9b, for GNU/Linux 3.2.0, with debug_info, not stripped
```

If you experience issues with cross-building, please provide detailed error logs.

**Comment by ThomasHeinrichSchmidt** [comment]
Thanks I tried that and received 
`# tmp/hello`   
`FATAL: kernel too old`      
`Aborted`      
on the target system. It has the same kernel as yours:
`# cat /proc/version`   
 `Linux version 2.6.35.4 (root@dev2.mediayou.net) (gcc version 4.2.1) #1137 PREEMPT Fri Apr 8 15:12:27 CST 2016`      
When I'm looking at another (working, alredy provided) target program I find
`# thomas@kiesel:~/Dev$ file LCMINIT`
`LCMINIT: ELF 32-bit LSB executable, ARM, EABI4 version 1 (SYSV), statically linked, stripped` 
My own executable shows 
`thomas@kiesel:~/Dev$ file hello`
`helloarm: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, for GNU/Linux 3.2.0, BuildID[sha1]=ad2611e4b8a40e853ba902342cd8ad7649dfb800, not stripped`
I guess I'll need to build for Linux 2.6 and not 3.2 - what do you think?

**Comment by ThomasHeinrichSchmidt** [comment]
I've now successfully used [musl-cross-make](https://github.com/richfelker/musl-cross-make) to build TARGET = arm-linux-musleabi
In this way I was able to build
`arm-linux-musleabi-gcc -Wall -g -static hello.c -o hello`
and this finally ran succesfully on the iradio system:
```
      # ls -le tmp/hello
      -rw-r--r--    1     18460 Wed Sep 16 18:50:03 2020 tmp/hello
      # chmod +x tmp/hello
      # tmp/hello
      Hello World
```

**Comment by kayrus** [comment]
@ThomasHeinrichSchmidt great. I'm glad that you resolved your problem. I'm closing the issue. Feel free to ask if you have any further questions.
