### ISSUE TITLE
[Question] Is it possible to remotely switch the radio on/off?

### ISSUE THREAD

**Issue by wsw70** [kayrus/iradio#3]
I have a Digital Ocean radio that matches your program. I would like to automate its switch on and off (from a home automation system). 

Would you know if this is possible? (I did not find anything related in your README so I believe the answer is 'no', but I masking just in case). Thanks!

**Comment by kayrus** [comment]
Do you want to automate the play/stop actions? I believe it is possible, but not with my program. My program just generates the binary playlist from a user friendly CSV file. I haven't researched the play control protocol.

**Comment by wsw70** [comment]
Thank you for the fast answer. I will investigate further then. Thanks!
