### ISSUE TITLE
Dump of Firmware

### ISSUE THREAD

**Issue by thatsitipl** [kayrus/iradio#4]
Could you provide a dump of the original firmware.
I have an device with an similar layout and wanted to know what they change.
And the password password doesn't work anymore.
Here is the passwd file.
[passwd.txt](https://github.com/kayrus/iradio/files/8054636/passwd.txt)
I've tried cracking it but they used something better and it doesn't make sense to let my pc run 24/7.

I would appreciate any replay.

**Comment by thatsitipl** [comment]
The firmware was dumped using an spi flash reader.

**Comment by kayrus** [comment]
if you were able to dump firmware, then you can write it back with updated passwd file, right?

**Comment by thatsitipl** [comment]
I wasn’t able to compress it and it didn’t boot anymore

**Comment by thatsitipl** [comment]
Here is a dump of the original firmware.
[radio.zip](https://github.com/kayrus/iradio/files/8061981/radio.zip)
